export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTRAR_PROJETO = "CADASTRAR_PROJETOS"
export const ALTERAR_PROJETO = "ALTERAR_PROJETOS"
export const REMOVER_PROJETO = "REMOVER_PROJETO"

export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const CADASTRAR_TAREFAS = "CADASTRAR_TAREFAS"
